#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#
# Runs linting on staged files. The specific commands to run are configured
# in `.lintstagedrc.cjs`.
#
# (The project is so small that we could perhaps get rid of lint-staged
# and lint the entire repository on every commit.)
#
npx lint-staged || exit 1

#
# Runs svelte-check on the entire project. It is not possible to run this on
# just the staged filed.
#
npm run check || exit 1
